### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by cmbaron** [davidfoliveira/node-solidqueue#1]
Any chance you'd be willing to release this module under the [Apache](http://www.apache.org/licenses/LICENSE-2.0) or [MIT](https://opensource.org/licenses/MIT) licenses?

**Comment by davidfoliveira** [comment]
Hi. May I know which characteristics of these licenses do you need? Thanks.

**Comment by davidfoliveira** [comment]
Anyway, the license was changed to MIT. Thanks.
